# Vorbereitung Dataset für die Übungsaufgabe

In [9]:
import numpy as np
np.random.seed(42)

try:
    x2=np.loadtxt('x_dataset.csv',delimiter=',')
    y2=np.loadtxt('y_dataset.csv',dtype=np.int64,delimiter=',')
except:
    print(f"Bitte Speichern Sie die CSV Datein im gleichen Ordner, wie diese Datei")

else:
    print(f"Alles ist für die Übung vorbereitet")

from sklearn.datasets import load_breast_cancer
dataset = load_breast_cancer()
x = dataset.data
y = dataset.target



Alles ist für die Übung vorbereitet


C:\Users\richard.stritzke\AppData\Local\Temp\ipykernel_5840\1018993737.py:6: DeprecationWarning: loadtxt(): Parsing an integer via a float is deprecated.  To avoid this warning, you can:
    * make sure the original data is stored as integers.
    * use the `converters=` keyword argument.  If you only use
      NumPy 1.23 or later, `converters=float` will normally work.
    * Use `np.loadtxt(...).astype(np.int64)` parsing the file as
      floating point and then convert it.  (On all NumPy versions.)
  (Deprecated NumPy 1.23)
  y2=np.loadtxt('y_dataset.csv',dtype=np.int64,delimiter=',')


## Aufgabe 1
Verwenden Sie Grid Search um einen Random Forest zu erstellen. Nutzen Sie dazu folgende Parameter:
- #Anzahl der Bäume= 100
- Kriterium: gini, entropy
- Maximale Tiefe: 2-8
- Mindesanzahl an Datenpunkten: 10-20
- Kreuzvalidierung: 10
- n_jobs=-1
- Aufteilung des Datasets: train:70%, test:30%

Rechenzeit: ca. 50s
  

{'criterion': 'gini', 'max_depth': 6, 'min_samples_leaf': 10, 'n_estimators': 100}
0.9372435897435898


## Aufgabe 2
Trainieren Sie mit den erlernten Parametern nochmals einen Random Forest. Sie können die besten Parameter direkt beim Aufruf des Objektes mit **grid_cv.best_params übergeben. Bewerten Sie die Genauigkeit des Algorithmus.

Accuracy: 0.9707602339181286


## Aufgabe 3
Bestimmen Sie die Confusion Matrix für den Random Forest. Interpretieren Sie das Ergebnis der Confussion Matrix

[[ 59   4]
 [  1 107]]


## Aufgabe 4
Wiederholen Sie die Aufgabe erneut mit dem zweiten Dataset <b>x2 und y2.</b>

- #Anzahl der Bäume= 120
- Kriterium: gini, entropy
- Maximale Tiefe: 5
- Mindesanzahl an Datenpunkten: 10
- Kreuzvalidierung: 10
- n_jobs=-1
- Aufteilung des Datasets: train:70%, test:30%

Rechenzeit: ca. 2min

{'criterion': 'gini', 'max_depth': 5, 'min_samples_leaf': 10, 'n_estimators': 120}
0.7685714285714285
Accuracy: 0.7693333333333333


[[2020  102   54  171  104   55]
 [  50 1925  175   54  202  121]
 [ 121  177 1900  150  141   68]
 [  81   36  104 1862  136  233]
 [ 155  121   95   80 1944   97]
 [ 133   55  133  165   91 1889]]
